config/routes.rb
Rubyblog::Application.routes.draw do
  resources :users

  resources :tags

  resources :categories

  resources :authors

  resources :articles do
    resources :comments
    member do 
      get :vote
    end
  end
  
  resources :sessions
    
  get '/tags' => 'tags#index'
  get '/login' => 'sessions#new' # new is the file path new.html.erb You can change this to index if you want, just make sure you move your login page to index.html.erb
  post '/login' => 'sessions#create' # creates new session
  get '/logout' => 'sessions#destroy' # Destroys the users session

   root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
    
  attr_accessible :body, :title, :author_id, :category_id, :tag_tokens
  belongs_to :author
  belongs_to :user
  belongs_to :category
  has_many :comments, :dependent => :destroy
  has_many :article_tags, :dependent => :destroy
  has_many :tags, :through => :article_tags
  has_many :votes
  
    acts_as_textcaptcha   :api_key     => '6ssjenchqao0cc0ko4oo8wgkwbn930p0',
                          :bcrypt_salt => '$2a$10$7ZHhFliCIWigF7GF3rdtbu'
  
  validates_presence_of :title, :message => " - you need a title"
  validates_presence_of :body, :message => " -you have to write something in your post!"
   
  def author_name
    self.author.full_name if self.author
  end
  
  def formatted_created_at
 	    self.created_at.strftime('%a. %b %d at %I:%M%p') if self.created_at
  end
  
  def tag_tokens
   	self.tags.collect{|t| t.name}.join(", ")
  end
  
  def tag_tokens=(tags_delimited)
   	tags_delimited.split(",").each do |string|
        	self.article_tags.build(:tag => Tag.find_or_create_by_name(string.strip.downcase))
   	end   	
  end
  
  def upvote
    self.increment!(:up_votes)
  end
  
  def downvote
    self.decrement!(:down_votes)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order("created_at DESC").paginate({:page => params[:page], :per_page => 10})

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end
  
  def vote
        @article = Article.find(params[:id])
          if params[:vote].to_i < 0 
            @article.downvote
          else
            @article.upvote
          end
          redirect_to articles_path
        end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new
    @article.textcaptcha
    


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id],)
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])
    
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
<% if @article.errors.any? %>
  <div class="error_messages">
	<p>There was a problem:</p>
	  <% for message in @article.errors.full_messages %>
		<p><%= message %></p>
	  <% end %>
	</ul>
  </div>
<% end %>	
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, :class => 'text_area' %>
    </div>
  </div>
<%= textcaptcha_fields(f) do %>
  <div class="field">
    <%= f.label :spam_answer, @article.spam_question %><br/>
    <%= f.text_field :spam_answer, :value => '' %>
  </div>
 <% end %>
  <% if can? :update, @article %>
  <div class="control-group">
    <%= f.label :author_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :author_id, Author.all.collect{|a| [a.full_name, a.id] } %>
    </div>
  </div>
 <% end %>
 <% if can? :update, @article %>
 <div class="control-group">
    <%= f.label :category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :category_id, Category.all.collect{|a| [a.name, a.id]} %>
    </div>
</div>
<% end %>

  <div class="control-group">
 	<%= f.label :add_your_tags, :class => 'control-label' %>
    <div class="controls">
 	  <%= f.text_field :tag_tokens, :class => 'text_field' %>
    </div>
</div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary', :confirm => "Did you remember to add tags to your post? Also, You can't edit after posting, so make sure everything is perfect!" %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
       articles_path, :confirm => "Do you actually want to cancel? Your post will be lost!", :class => 'btn' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = @article.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<h1>Uncooked Blog</h1><%= image_tag 'egg.png', :id => 'picOne' %><%= image_tag 'egg2.png', :id => 'picTwo'  %>​
<h3>It Doesn't Get Any Rawer Than This</h3>
<hr>
<%- model_class = Article.new.class -%>
	<div class="headline">
		<p>What makes this blog so Raw? Anyone can post anything, anytime. No rules! 
		<p>There is a catch though - you can't edit or delete your posts.</p>
		<p>So that's it. Post away! </p>
	</div>

<%= will_paginate @articles, :id => 'pagination' %>

<!-- <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>


  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:vote) %></th>
	  <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:article) %></th>
	  <th><%= model_class.human_attribute_name(:tags) %></th>
      <% if can? :update, @article %>
	  <th><%= model_class.human_attribute_name(:author_id) %></th>
	  <% end %>
      <th><%= model_class.human_attribute_name(:published) %></th>
     <% if can? :update, @article %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
	<% end %>
    </tr>
  </thead> -->
  
    <% @articles.each do |article| %>
<div class="articlebox">
<!--  
<%= link_to 'I like this', vote_article_path(article) + '?vote=1' %><br>
<%= link_to 'I hate this', vote_article_path(article) + '?vote=-1' %>
-->	

	<span id='date'>
		Posted: <%= article.formatted_created_at %>	
	</span>
    	<%= link_to article.title, article_path(article), :id => 'articletitle' %>
    <span id='articlebody'>	
		<%= markdown article.body %>
	</span>	 
		<%= "Tags:" if article.tags.any? %>
	 	<% article.tags.each do |tag| %>
	<span class="articletagbox">	
	    <%= tag.name %>
	</span>	
	<% end %>       
	  <% if can? :update, @article %> <!-- Using Can Can gem to determine if a user has edit/destroy permissions -->
 	  	<%= article.author_name %>
	  <% end %>
	  <% if can? :update, @article %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_article_path(article), :class => 'btn btn-mini' %>
	  <% end %>	
	  <% if can? :update, @article %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      article_path(article),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
	  <% end %>
</div><!-- END ARTICLEBOX -->
      <% end %>
<!-- <%= link_to t('.new', :default => t("helpers.links.new")),
            new_article_path,
            :class => 'btn btn-primary' %> -->

app/views/articles/new.html.erb
<%- model_class = @article.class -%>
<h2><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h2>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = @article.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:title) %>:</strong><br>
  <%= @article.title %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:body) %>:</strong><br>
  <%= markdown @article.body %>
</p>

<!-- viewing posted comments on articles - see views/comments/_comments.htmp.erb for code -->
<strong><%= model_class.human_attribute_name(:comments) %></strong><br>
<%= render @article.comments %>
<!-- end viewing comments posted to articles -->

<!-- posting a comment to an article -->
<h2>Add a comment:</h2>
<%= render "comments/form" %>
<!-- end posting a comment to an article -->

<% if can? :update, @article %>
<p>
  <strong><%= model_class.human_attribute_name(:author_id) %>:</strong><br>
  <%= @article.author_name %>
</p>
<% end %>
<p>
  <table class="table table-striped">
	<thead>
      <tr>
	    <th><strong><%= model_class.human_attribute_name(:tags) %>:</strong></th>
	  </tr>
	</thead>
  <tbody>
  <% @article.tags.each do |tag| %>
    <tr>
      <td><%= link_to tag.name, tag_path(tag) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn'  %>
  <% if can? :update, @article %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn' %>
  <% end %>
  <% if can? :update, @article %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
  <% end %>
</div>