config/routes.rb
Rubyblog::Application.routes.draw do
  resources :users

  resources :tags

  resources :categories

  resources :authors

  resources :articles do
    resources :comments
    member do 
      get :vote
    end
  end
  
  resources :sessions
    
  get '/tags' => 'tags#index'
  get '/login' => 'sessions#new' # new is the file path new.html.erb You can change this to index if you want, just make sure you move your login page to index.html.erb
  post '/login' => 'sessions#create' # creates new session
  get '/logout' => 'sessions#destroy' # Destroys the users session

   root :to => 'articles#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Uncooked Blog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">

<!-- FONT FILES -->
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<!-- END FONT FILES -->

<!-- Google Analytics Code -->
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-31861012-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script> 
	<!-- End of Google Analytics Code -->
</head>
  <body>
    <div id="container"> <!-- BEGIN CONTAINER DIV -->
      <%= link_to "Home", articles_path, :class => 'button orange glossy back' %>
	  <%= link_to "Articles", articles_path, :class => 'button blue glossy' %>
	  <% if can? :update, @category%>
	  <%= link_to "Categories", categories_path, :class => 'button blue glossy' %>
	  <% end %>
	  <%= link_to "Tags", tags_path, :class => 'button blue glossy' %>
      <% if can? :update, @author %>
      <%= link_to "Authors", authors_path, :class => 'button blue glossy' %>
	  <% end %>
	<span id="new"> 
	 <%= link_to t('.new article', :default => t("helpers.links.new article")),
	            new_article_path, :class => 'button pink glossy morph', "data-icon" => '' %>
	</span>
	<hr>
       <%= yield %>
    <br>
      <footer>
        <p>No &copy;, no rights reserved </p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
	</div><!-- END CONTAINER -->
  </body>
</html>